# Generated by Django 4.2.25 on 2025-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, help_text='e.g., E-101-049. Used for teacher verification.', max_length=100, null=True),
        ),
    ]
