# Generated by Django 4.2.25 on 2025-11-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quizquestion_quizattempt'),
        ('courses', '0002_remove_course_instructor_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('Text', 'Text Content (Office Word-এর মতো)'), ('Video', 'Video (YouTube/Vimeo)'), ('File', 'File (PDF/Slides)'), ('Practice', 'Practice (Quiz or Coding Problem)')], default='Text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='lessons/files/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
                ('practice', models.ForeignKey(blank=True, help_text='এই পাঠটি সম্পূর্ণ করার জন্য একটি পরীক্ষা বা কুইজ সিলেক্ট করুন।', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
