# Generated by Django 4.2.25 on 2025-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_b2c_public',
            field=models.BooleanField(default=False, help_text='Is this course available for purchase on the B2C marketplace?'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for B2C marketplace. 0.00 for B2B.', max_digits=10),
        ),
    ]
