# Generated by Django 4.2.25 on 2025-11-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quizquestion_quizattempt'),
        ('tenants', '0001_initial'),
        ('courses', '0004_course_is_b2c_public_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Text', 'Text Content (Office Word-like)'), ('Video', 'Video (YouTube/Vimeo)'), ('File', 'File (PDF/Slides)'), ('Practice', 'Practice (Quiz or Coding Problem)')], default='Text', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='practice',
            field=models.ForeignKey(blank=True, help_text='Select an assessment or quiz for this lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.assessment'),
        ),
    ]
