# Generated by Django 4.2.25 on 2025-11-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_invite_code'),
        ('courses', '0005_remove_course_department_course_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='organization',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.department'),
        ),
    ]
